import { useMemo, useState, type FormEvent } from 'react';
import { api, itemsOf, orgPath } from '../api';
import { Button, ConfirmDialog, Empty, ErrorBox, Field, Loading, PageHeader, Panel, useResource } from '../components';
import { addDays, dateRu } from '../format';
import type { Paged, Property } from '../types';

interface Block {id:string;unit_id:string;from:string;to:string;reason?:string}
const today=()=>{const now=new Date();return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;};
export function BlockPage({orgId,canWrite=true}:{orgId:string;canWrite?:boolean}) {
  const properties=useResource<Paged<Property>|Property[]>(orgPath(orgId,'properties'));
  const blocks=useResource<Paged<Block>|Block[]>(orgPath(orgId,'availability-blocks'));
  const units=useMemo(()=>itemsOf(properties.data||[]).flatMap(property=>(property.units||[]).map(unit=>({...unit,property_name:property.name}))),[properties.data]);
  const [unitId,setUnitId]=useState('');const [from,setFrom]=useState(today());const [to,setTo]=useState(addDays(today(),1));const [reason,setReason]=useState('maintenance');const [note,setNote]=useState('');const [confirm,setConfirm]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState<unknown>(null);const [success,setSuccess]=useState('');
  function prepare(event:FormEvent){event.preventDefault();if(unitId&&to>from)setConfirm(true);}
  async function save(){setBusy(true);setError(null);setSuccess('');const reasonLabel=reason==='maintenance'?'Ремонт':reason==='owner'?'Владелец':'Другое';try{await api(orgPath(orgId,'availability-blocks'),{method:'POST',body:{unit_id:unitId,from,to,reason:note.trim()?`${reasonLabel}: ${note.trim()}`:reasonLabel}});setSuccess('Блокировка сохранена. Проверьте доставку доступности на каждый подключённый канал.');setConfirm(false);blocks.reload();}catch(caught){setError(caught);setConfirm(false);}finally{setBusy(false);}}
  return <><PageHeader eyebrow="Шахматка" title="Блокировка дат" description="Закройте номер для ремонта или владельца. Блокировка не создаёт доходную бронь."/>
    {Boolean(error)&&<ErrorBox error={error}/>}{success&&<div className="notice notice-success" role="status">{success}</div>}
    <div className="two-column"><Panel title="Новый блок">{properties.loading&&<Loading/>}{Boolean(properties.error)&&<ErrorBox error={properties.error} retry={properties.reload}/>} {!properties.loading&&!properties.error&&units.length===0&&<Empty title="Нет номеров" detail="Добавьте объект и номер для блокировки дат."/>}<form onSubmit={prepare} className="form-grid"><Field label="Номер"><select required value={unitId} onChange={event=>setUnitId(event.target.value)}><option value="">Выберите номер</option>{units.map(unit=><option key={unit.id} value={unit.id}>{unit.property_name} · {unit.name}</option>)}</select></Field><Field label="Причина"><select value={reason} onChange={event=>setReason(event.target.value)}><option value="maintenance">Ремонт</option><option value="owner">Владелец</option><option value="other">Другое</option></select></Field><Field label="С"><input type="date" value={from} onChange={event=>setFrom(event.target.value)}/></Field><Field label="До (дата выезда)" error={to<=from?'Конец должен быть позже начала.':undefined}><input type="date" min={addDays(from,1)} value={to} onChange={event=>setTo(event.target.value)}/></Field><Field label="Уточнение причины" className="span-all"><textarea rows={3} value={note} onChange={event=>setNote(event.target.value)} maxLength={450}/></Field><div className="span-all"><Button type="submit" variant="primary" disabled={!canWrite||!unitId||to<=from||busy}>Проверить и закрыть даты</Button></div></form></Panel>
      <Panel title="Текущие блокировки">{blocks.loading?<Loading/>:blocks.error?<ErrorBox error={blocks.error} retry={blocks.reload}/>:itemsOf(blocks.data||[]).length?<div className="record-list">{itemsOf(blocks.data||[]).map(block=><div className="record-row" key={block.id}><div className="record-main"><strong>{units.find(unit=>unit.id===block.unit_id)?.name||'Номер'}</strong><small>{dateRu(block.from)} — {dateRu(block.to)}</small></div><span>{block.reason||'Закрыто'}</span></div>)}</div>:<Empty title="Блокировок пока нет" detail="Закрытые даты появятся здесь и в шахматке."/>}</Panel></div>
    {confirm&&<ConfirmDialog title="Закрыть выбранные даты?" description={<p>{units.find(unit=>unit.id===unitId)?.name}: {dateRu(from)} — {dateRu(to)}; пересечение с бронью сервер отклонит.</p>} onCancel={()=>setConfirm(false)} onConfirm={()=>void save()} busy={busy} confirmLabel="Закрыть даты"/>}
  </>;
}
