import { useMemo, useState, type FormEvent } from 'react';
import { api, itemsOf, orgPath } from '../api';
import { Badge, Button, Empty, ErrorBox, Field, Loading, PageHeader, Panel, useResource } from '../components';
import type { Paged, Property } from '../types';

interface Capabilities {occupancyImport:boolean;occupancyExport:boolean;reservationImport:boolean;reservationCancel:boolean;rateWrite:boolean;restrictionWrite:boolean;paymentWrite:boolean;webhook:boolean;recurrenceExpansion:boolean}
interface Connector {id:string;name:string;category:string;implementation:string;capabilities:Capabilities;productionReady:boolean}
interface Connection {id:string;service_code:string;provider_name?:string;mechanism?:string;display_name?:string;status:string;status_message?:string;implementation?:string;capabilities?:Capabilities|null;last_success_at?:string|null;last_error_code?:string|null;version?:number;mappings?:Array<{id:string;unit_id:string;unit_name:string;property_name:string}>}

const statusText:Record<string,string>={access_required:'Нужен допуск',verification_pending:'Проверка не выполнена',healthy:'Чтение подтверждено',conflict:'Конфликт',degraded:'Ошибка обмена',disabled:'Отключено'};
const capabilityNames:Record<keyof Capabilities,string>={occupancyImport:'Занятость от источника',occupancyExport:'Календарь наружу',reservationImport:'Брони от источника',reservationCancel:'Отмена через канал',rateWrite:'Цены наружу',restrictionWrite:'Ограничения наружу',paymentWrite:'Платежи',webhook:'Входящие события',recurrenceExpansion:'Повторения iCal'};
export function ConnectionsPage({orgId,mapping=false,canManage=true}:{orgId:string;mapping?:boolean;canManage?:boolean}) {
  const list=useResource<Paged<Connection>|Connection[]>(orgPath(orgId,'connections'));
  const catalog=useResource<Paged<Connector>|Connector[]>(orgPath(orgId,'connections/capabilities'));
  const properties=useResource<Paged<Property>|Property[]>(orgPath(orgId,'properties'));
  const connections=itemsOf(list.data||[]),connectors=itemsOf(catalog.data||[]);
  const units=useMemo(()=>itemsOf(properties.data||[]).flatMap(property=>(property.units||[]).map(unit=>({...unit,property_name:property.name}))),[properties.data]);
  const [form,setForm]=useState<'ical'|'partner'|null>(null);const [serviceCode,setServiceCode]=useState('INT-ICAL');const [displayName,setDisplayName]=useState('');const [unitId,setUnitId]=useState('');const [feedUrl,setFeedUrl]=useState('');const [selectedId,setSelectedId]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState<unknown>(null);const [success,setSuccess]=useState('');
  const detail=useResource<Connection>(mapping&&selectedId?orgPath(orgId,`connections/${selectedId}`):null);
  const chosen=connectors.find(item=>item.id===serviceCode);
  async function create(event:FormEvent){event.preventDefault();setBusy(true);setError(null);setSuccess('');try{
    if(form==='ical')await api(orgPath(orgId,'connections/ical'),{method:'POST',body:{service_code:serviceCode,display_name:displayName,unit_id:unitId,feed_url:feedUrl,poll_interval_seconds:900}});
    else await api(orgPath(orgId,'connections'),{method:'POST',body:{service_code:serviceCode,display_name:displayName,unit_id:unitId||undefined}});
    setFeedUrl('');setDisplayName('');setUnitId('');setForm(null);setSuccess(form==='ical'?'Настройки iCal сохранены. Дождитесь первого подтверждённого чтения календаря.':'Запрос доступа сохранён. Обмен станет доступен после подтверждения прав поставщика.');list.reload();
  }catch(caught){setError(caught);}finally{setBusy(false);}}
  function begin(kind:'ical'|'partner'){setForm(kind);setError(null);setSuccess('');setServiceCode(kind==='ical'?'INT-ICAL':connectors.find(item=>item.implementation==='partner_access_pending')?.id||'');}
  return <><PageHeader eyebrow="Каналы" title={mapping?'Сопоставление объектов':'Подключения'} description="У каждого соединения отдельные возможности и время последнего успешного обмена. iCal передаёт занятость; цена и платежи требуют другого подтверждённого механизма." actions={!mapping&&canManage?<div className="inline-actions"><Button onClick={()=>begin('ical')}>+ iCal</Button><Button variant="primary" onClick={()=>begin('partner')} disabled={!connectors.some(item=>item.implementation==='partner_access_pending')}>Запросить партнёрский доступ</Button></div>:undefined}/>
    {Boolean(error)&&<ErrorBox error={error}/>}{success&&<div className="notice notice-success" role="status">{success}</div>}
    {form&&<Panel title={form==='ical'?'Подключить календарь iCal':'Запросить доступ к провайдеру'} className="action-panel"><form className="form-grid" onSubmit={create}><Field label="Провайдер"><select required value={serviceCode} onChange={event=>setServiceCode(event.target.value)}>{connectors.filter(item=>form==='ical'?item.implementation==='ical_available':item.implementation==='partner_access_pending').map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Название подключения"><input required value={displayName} onChange={event=>setDisplayName(event.target.value)} maxLength={120}/></Field><Field label="Номер"><select required={form==='ical'} value={unitId} onChange={event=>setUnitId(event.target.value)}><option value="">{form==='ical'?'Выберите номер':'Весь доступный портфель'}</option>{units.map(unit=><option key={unit.id} value={unit.id}>{unit.property_name} · {unit.name}</option>)}</select></Field>{form==='ical'&&<Field label="HTTPS-ссылка календаря" className="span-all" hint="Ссылка содержит доступ к занятости. Она передаётся только серверу и после сохранения не отображается."><input type="password" autoComplete="off" required value={feedUrl} onChange={event=>setFeedUrl(event.target.value)} /></Field>}<div className="span-all notice notice-warning">{form==='ical'?'Первое сохранение не доказывает успешный обмен. Статус изменится после отдельной проверки.':'Этот шаг фиксирует потребность в подключении. Партнёрский API и право доступа пока не подтверждены.'}</div><div className="span-all inline-actions"><Button type="button" onClick={()=>{setFeedUrl('');setForm(null);}}>Отмена</Button><Button variant="primary" type="submit" disabled={busy||!serviceCode||!displayName.trim()||(form==='ical'&&(!unitId||!feedUrl))}>{busy?'Сохраняем…':form==='ical'?'Сохранить iCal':'Сохранить запрос'}</Button></div></form>{chosen&&<p className="muted">Статус механизма: {chosen.implementation}.</p>}</Panel>}
    {mapping&&<Panel title="Сохранённые привязки"><Field label="Подключение"><select value={selectedId} onChange={event=>setSelectedId(event.target.value)}><option value="">Выберите подключение</option>{connections.map(item=><option value={item.id} key={item.id}>{item.display_name||item.provider_name||item.service_code}</option>)}</select></Field>{detail.loading&&<Loading/>}{Boolean(detail.error)&&<ErrorBox error={detail.error} retry={detail.reload}/ >}{detail.data&&<div className="record-list">{detail.data.mappings?.length?detail.data.mappings.map(item=><div className="record-row" key={item.id}><div className="record-main"><strong>{item.property_name} · {item.unit_name}</strong><small>Наш номер связан с этим календарём или провайдером.</small></div></div>):<Empty title="Привязок нет" detail="Связь с номером создаётся при настройке поддерживаемого механизма."/>}</div>}</Panel>}
    {list.loading&&<Loading/>}{Boolean(list.error)&&<ErrorBox error={list.error} retry={list.reload}/>}{!list.loading&&!list.error&&<div className="connection-grid">{connections.length?connections.map(item=><Panel key={item.id} title={item.display_name||item.provider_name||item.service_code} actions={<Badge state={item.status}>{statusText[item.status]||item.status}</Badge>}><p className="muted">{item.provider_name||item.service_code} · {item.mechanism==='ical'?'iCal':'Партнёрский доступ'}</p><p>{item.status_message||'Состояние ожидает проверки.'}</p><p className="muted">Успешный обмен: {item.last_success_at?new Date(item.last_success_at).toLocaleString('ru-RU'):'ещё не подтверждён'}</p>{item.last_error_code&&<div className="notice notice-warning">Ошибка обмена: {item.last_error_code}</div>}<div className="chip-row">{item.capabilities?Object.entries(item.capabilities).filter(([,enabled])=>enabled).map(([capability])=><span className="chip" key={capability}>{capabilityNames[capability as keyof Capabilities]||capability}</span>):<span className="muted">Возможности ещё не подтверждены.</span>}</div></Panel>):<Empty title="Подключений пока нет" detail="Выберите доступный механизм или зафиксируйте запрос партнёрского допуска."/>}</div>}
  </>;
}
